### ISSUE TITLE
configure.ac puts C++ flags into CFLAGS in coinsoplex.pc

### ISSUE THREAD

**Issue by mkoeppe** [coin-or-tools/ThirdParty-SoPlex#2]
This causes the following warnings when compiling ThirdParty-SCIP:
cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C

(This is with gcc 4.9.2 on Mac OS X.)

**Comment by svigerske** [comment]
The problem is that, as far as I know, there is no way to distinguish between different languages (C,C++,Fxy) in the pkg-config file. It's always just CFLAGS, so I put also some C++ arguments in there (it generates just warnings, which is acceptable or COIN-OR :-)).

One could move the logic about adding this flag into the code that uses SoPlex. There is probably no pragma one could put into the SoPlex headers to tell the compiler that the following is C++11 (?).

**Comment by svigerske** [comment]
Adding this flag was removed with 2a6581abd69
